# Generated by Django 6.0.7 on 2026-09-01 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='available_cash',
            new_name='total_realized_profit',
        ),
        migrations.RenameField(
            model_name='portfolioposition',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='portfolioposition',
            name='pyramid_level',
        ),
        migrations.RemoveField(
            model_name='portfolioposition',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfolioposition',
            name='current_stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioposition',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='portfolioposition',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='portfolioposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('shares', models.IntegerField()),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('pnl_value', models.FloatField()),
                ('pnl_percent', models.FloatField()),
                ('exit_reason', models.CharField(default='Manual Exit', max_length=100)),
                ('date_closed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
