import os
import pandas as pd
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from .models import Account, PortfolioPosition, TradeJournal

def get_latest_prices():
    """Reads the EOD CSV generated by your bot to get real-time prices."""
    # Maps directly to nse-trading-bot/data/nse_historical_data.csv
    csv_path = os.path.abspath(os.path.join(settings.BASE_DIR, "..", "data", "nse_historical_data.csv"))
    prices = {}
    if os.path.exists(csv_path):
        try:
            df = pd.read_csv(csv_path)
            latest = df.drop_duplicates(subset=['ticker'], keep='last')
            for _, row in latest.iterrows():
                prices[row['ticker']] = row['close']
        except Exception as e:
            print(f"Error reading market CSV: {e}")
    return prices

@login_required
def dashboard(request):
    # Ensure user has an account profile
    account, _ = Account.objects.get_or_create(user=request.user)
    
    # Fetch all open & pending positions
    positions = PortfolioPosition.objects.filter(user=request.user).order_by('-date_added')
    latest_prices = get_latest_prices()
    
    portfolio_data = []
    total_invested = 0.0
    current_value = 0.0
    
    for pos in positions:
        # Fallback to entry price if market price isn't in CSV yet
        current_price = latest_prices.get(pos.ticker, pos.entry_price)
        
        invested_val = pos.shares * pos.entry_price
        current_val = pos.shares * current_price
        pnl_val = current_val - invested_val
        pnl_pct = (pnl_val / invested_val * 100) if invested_val > 0 else 0.0
        
        # Only add OPEN positions to the master portfolio totals
        if pos.status == 'OPEN':
            total_invested += invested_val
            current_value += current_val
            
        portfolio_data.append({
            'id': pos.id,
            'ticker': pos.ticker,
            'shares': pos.shares,
            'entry_price': pos.entry_price,
            'current_price': current_price,
            'current_stop_loss': pos.current_stop_loss,
            'invested_value': invested_val,
            'current_value': current_val,
            'pnl_value': pnl_val,
            'pnl_percent': pnl_pct,
            'status': pos.status
        })
        
    net_gain = current_value - total_invested
    net_gain_pct = (net_gain / total_invested * 100) if total_invested > 0 else 0.0

    context = {
        'portfolio': portfolio_data,
        'total_invested': total_invested,
        'current_value': current_value,
        'net_gain': net_gain,
        'net_gain_pct': net_gain_pct,
        'total_realized': account.total_realized_profit,
        'radar_list': [] # We will hook up the algorithm signals here next!
    }
    
    return render(request, 'frontend/dashboard.html', context)

@login_required
def add_position(request):
    """Executes a new trade logging from the frontend Calculator Modal."""
    if request.method == 'POST':
        ticker = request.POST.get('ticker').upper()
        shares = int(request.POST.get('shares'))
        entry_price = float(request.POST.get('entry_price'))
        stop_loss = request.POST.get('stop_loss')
        status = request.POST.get('status', 'OPEN')
        
        PortfolioPosition.objects.create(
            user=request.user,
            ticker=ticker,
            shares=shares,
            entry_price=entry_price,
            current_stop_loss=float(stop_loss) if stop_loss else None,
            status=status
        )
        messages.success(request, f"Trade logged: {shares} units of {ticker}.")
    return redirect('dashboard')

@login_required
def edit_position(request, position_id):
    """Updates an existing position's parameters."""
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        pos.ticker = request.POST.get('ticker').upper()
        pos.shares = int(request.POST.get('shares'))
        pos.entry_price = float(request.POST.get('entry_price'))
        
        stop_loss = request.POST.get('stop_loss')
        pos.current_stop_loss = float(stop_loss) if stop_loss else None
        pos.status = request.POST.get('status', 'OPEN')
        
        pos.save()
        messages.success(request, f"{pos.ticker} ledger updated.")
    return redirect('dashboard')

@login_required
def update_position_status(request, position_id):
    """Instantly promotes a PENDING order to an OPEN holding."""
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        action = request.POST.get('action')
        if action == 'confirm':
            pos.status = 'OPEN'
            pos.save()
            messages.success(request, f"{pos.ticker} order confirmed to OPEN.")
    return redirect('dashboard')

@login_required
def delete_position(request, position_id):
    """Permanently purges a mistake/canceled order from the ledger."""
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        pos.delete()
        messages.success(request, "Position completely purged from ledger.")
    return redirect('dashboard')

@login_required
def trade_journal(request):
    """Renders the historical ledger of closed trades and calculates performance metrics."""
    journal_entries = TradeJournal.objects.filter(user=request.user).order_by('-date_closed')
    
    total_trades = journal_entries.count()
    winning_trades = journal_entries.filter(pnl_value__gt=0).count()
    win_rate = (winning_trades / total_trades * 100) if total_trades > 0 else 0.0
    
    account, _ = Account.objects.get_or_create(user=request.user)
    
    context = {
        'entries': journal_entries,
        'total_trades': total_trades,
        'win_rate': win_rate,
        'total_realized': account.total_realized_profit,
    }
    return render(request, 'frontend/journal.html', context)

@login_required
def close_position(request, position_id):
    """Calculates final P&L, moves a position to the Journal, and deletes the open record."""
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        exit_price = float(request.POST.get('exit_price'))
        exit_reason = request.POST.get('exit_reason', 'Manual Exit')
        
        # Calculate final realized P&L
        invested_val = pos.shares * pos.entry_price
        exit_val = pos.shares * exit_price
        pnl_val = exit_val - invested_val
        pnl_pct = (pnl_val / invested_val * 100) if invested_val > 0 else 0.0
        
        # 1. Log to Trade Journal
        TradeJournal.objects.create(
            user=request.user,
            ticker=pos.ticker,
            shares=pos.shares,
            entry_price=pos.entry_price,
            exit_price=exit_price,
            pnl_value=pnl_val,
            pnl_percent=pnl_pct,
            exit_reason=exit_reason
        )
        
        # 2. Update Global Account Realized Profit
        account, _ = Account.objects.get_or_create(user=request.user)
        account.total_realized_profit += pnl_val
        account.save()
        
        # 3. Purge from active portfolio
        pos.delete()
        
        messages.success(request, f"{pos.ticker} closed. Realized P&L: KES {pnl_val:.2f} logged to journal.")
    return redirect('dashboard')