import os
import sys
import json
import datetime
import glob
import pandas as pd

# Add project root to Python path so 'src' can be imported when running manage.py
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib import messages
from django.conf import settings

from .models import Account, PortfolioPosition, TradeJournal
from src.notifications.gmail_alerts import dispatch_eod_summary_report

def get_latest_prices():
    """Reads the EOD CSV generated by the bot to get real-time prices."""
    csv_path = os.path.abspath(os.path.join(settings.BASE_DIR, "..", "data", "nse_historical_data.csv"))
    prices = {}
    if os.path.exists(csv_path):
        try:
            df = pd.read_csv(csv_path)
            latest = df.drop_duplicates(subset=['ticker'], keep='last')
            for _, row in latest.iterrows():
                prices[row['ticker']] = row['close']
        except Exception as e:
            print(f"Error reading market CSV: {e}")
    return prices

@login_required
def dashboard(request):
    account, _ = Account.objects.get_or_create(user=request.user)
    positions = PortfolioPosition.objects.filter(user=request.user).order_by('-date_added')
    latest_prices = get_latest_prices()
    
    portfolio_data = []
    total_invested = 0.0
    current_value = 0.0
    
    for pos in positions:
        current_price = latest_prices.get(pos.ticker, pos.entry_price)
        invested_val = pos.shares * pos.entry_price
        current_val = pos.shares * current_price
        pnl_val = current_val - invested_val
        pnl_pct = (pnl_val / invested_val * 100) if invested_val > 0 else 0.0
        
        if pos.status == 'OPEN':
            total_invested += invested_val
            current_value += current_val
            
        portfolio_data.append({
            'id': pos.id,
            'ticker': pos.ticker,
            'shares': pos.shares,
            'entry_price': pos.entry_price,
            'current_price': current_price,
            'current_stop_loss': pos.current_stop_loss,
            'invested_value': invested_val,
            'current_value': current_val,
            'pnl_value': pnl_val,
            'pnl_percent': pnl_pct,
            'status': pos.status
        })
        
    net_gain = current_value - total_invested
    net_gain_pct = (net_gain / total_invested * 100) if total_invested > 0 else 0.0

    context = {
        'portfolio': portfolio_data,
        'total_invested': total_invested,
        'current_value': current_value,
        'net_gain': net_gain,
        'net_gain_pct': net_gain_pct,
        'total_realized': account.total_realized_profit,
    }
    return render(request, 'frontend/dashboard.html', context)

@login_required
def add_position(request):
    """Executes trade logging, automatically consolidating with existing OPEN positions."""
    if request.method == 'POST':
        ticker = request.POST.get('ticker').upper()
        new_shares = int(request.POST.get('shares'))
        new_entry_price = float(request.POST.get('entry_price'))
        stop_loss = request.POST.get('stop_loss')
        status = request.POST.get('status', 'OPEN')
        
        parsed_stop_loss = float(stop_loss) if stop_loss else None

        existing_pos = PortfolioPosition.objects.filter(
            user=request.user, 
            ticker=ticker, 
            status='OPEN'
        ).first()

        if existing_pos and status == 'OPEN':
            old_shares = existing_pos.shares
            old_price = existing_pos.entry_price
            
            total_shares = old_shares + new_shares
            total_cost = (old_shares * old_price) + (new_shares * new_entry_price)
            new_avg_price = total_cost / total_shares if total_shares > 0 else new_entry_price
            
            existing_pos.shares = total_shares
            existing_pos.entry_price = new_avg_price
            if parsed_stop_loss:
                existing_pos.current_stop_loss = parsed_stop_loss
            existing_pos.save()
            
            messages.success(request, f"Consolidated {ticker}: Added {new_shares} units. New total: {total_shares} shares @ KES {new_avg_price:.2f}.")
        else:
            PortfolioPosition.objects.create(
                user=request.user,
                ticker=ticker,
                shares=new_shares,
                entry_price=new_entry_price,
                current_stop_loss=parsed_stop_loss,
                status=status
            )
            messages.success(request, f"Trade logged: {new_shares} units of {ticker}.")
            
    return redirect('dashboard')

@login_required
def edit_position(request, position_id):
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        pos.ticker = request.POST.get('ticker').upper()
        pos.shares = int(request.POST.get('shares'))
        pos.entry_price = float(request.POST.get('entry_price'))
        
        stop_loss = request.POST.get('stop_loss')
        pos.current_stop_loss = float(stop_loss) if stop_loss else None
        pos.status = request.POST.get('status', 'OPEN')
        
        pos.save()
        messages.success(request, f"{pos.ticker} ledger updated.")
    return redirect('dashboard')

@login_required
def update_position_status(request, position_id):
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        action = request.POST.get('action')
        if action == 'confirm':
            pos.status = 'OPEN'
            pos.save()
            messages.success(request, f"{pos.ticker} order confirmed to OPEN.")
    return redirect('dashboard')

@login_required
def delete_position(request, position_id):
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        pos.delete()
        messages.success(request, "Position completely purged from ledger.")
    return redirect('dashboard')

@login_required
def trade_journal(request):
    journal_entries = TradeJournal.objects.filter(user=request.user).order_by('-date_closed')
    
    total_trades = journal_entries.count()
    winning_trades = journal_entries.filter(pnl_value__gt=0).count()
    win_rate = (winning_trades / total_trades * 100) if total_trades > 0 else 0.0
    
    account, _ = Account.objects.get_or_create(user=request.user)
    
    context = {
        'entries': journal_entries,
        'total_trades': total_trades,
        'win_rate': win_rate,
        'total_realized': account.total_realized_profit,
    }
    return render(request, 'frontend/journal.html', context)

@login_required
def close_position(request, position_id):
    if request.method == 'POST':
        pos = get_object_or_404(PortfolioPosition, id=position_id, user=request.user)
        exit_price = float(request.POST.get('exit_price'))
        exit_reason = request.POST.get('exit_reason', 'Manual Exit')
        
        invested_val = pos.shares * pos.entry_price
        exit_val = pos.shares * exit_price
        pnl_val = exit_val - invested_val
        pnl_pct = (pnl_val / invested_val * 100) if invested_val > 0 else 0.0
        
        TradeJournal.objects.create(
            user=request.user,
            ticker=pos.ticker,
            shares=pos.shares,
            entry_price=pos.entry_price,
            exit_price=exit_price,
            pnl_value=pnl_val,
            pnl_percent=pnl_pct,
            exit_reason=exit_reason
        )
        
        account, _ = Account.objects.get_or_create(user=request.user)
        account.total_realized_profit += pnl_val
        account.save()
        
        pos.delete()
        messages.success(request, f"{pos.ticker} closed. Realized P&L: KES {pnl_val:.2f} logged to journal.")
    return redirect('dashboard')

@login_required
def control_room(request):
    csv_path = os.path.abspath(os.path.join(settings.BASE_DIR, "..", "data", "nse_historical_data.csv"))
    last_updated = None
    data_status = "OFFLINE"
    
    if os.path.exists(csv_path):
        timestamp = os.path.getmtime(csv_path)
        last_updated = datetime.datetime.fromtimestamp(timestamp)
        data_status = "ONLINE"
        
    open_positions = PortfolioPosition.objects.filter(user=request.user).count()
    closed_trades = TradeJournal.objects.filter(user=request.user).count()

    context = {
        'last_updated': last_updated,
        'data_status': data_status,
        'open_positions': open_positions,
        'closed_trades': closed_trades,
    }
    return render(request, 'frontend/control_room.html', context)

@login_required
def refresh_market_data(request):
    if request.method == 'POST':
        messages.success(request, "Market Data refresh sequence initiated.")
    return redirect('control_room')

@login_required
def dispatch_eod_manual(request):
    """Manually triggers and dispatches the EOD summary report from Control Room."""
    if request.method == 'POST':
        try:
            user_email = request.user.email or os.environ.get("GMAIL_RECIPIENT", "")
            username = request.user.username
            
            latest_prices = get_latest_prices()
            positions = PortfolioPosition.objects.filter(user=request.user, status='OPEN')
            open_pos_list = []
            total_equity = 0.0
            
            for p in positions:
                curr = latest_prices.get(p.ticker, p.entry_price)
                val = p.shares * curr
                total_equity += val
                open_pos_list.append({
                    'ticker': p.ticker,
                    'shares': p.shares,
                    'entry': p.entry_price,
                    'current': curr,
                    'pnl_val': val - (p.shares * p.entry_price)
                })
                
            account, _ = Account.objects.get_or_create(user=request.user)
            portfolio = {
                "total_equity": total_equity,
                "cash": 0.0,
                "realized_profit": account.total_realized_profit,
                "open_positions": open_pos_list
            }
            
            dispatch_eod_summary_report(
                recipient_email=user_email,
                username=username,
                portfolio=portfolio,
                all_signals=[],
                latest_prices=latest_prices
            )
            messages.success(request, "✅ EOD Closing Report successfully dispatched to your email!")
        except Exception as e:
            messages.error(request, f"❌ Failed to dispatch EOD report: {e}")
            
    return redirect('control_room')

@login_required
def clear_logs_manual(request):
    """Clears out runtime lock and log files from the logs directory."""
    if request.method == 'POST':
        try:
            logs_dir = os.path.abspath(os.path.join(settings.BASE_DIR, "..", "logs"))
            log_files = glob.glob(os.path.join(logs_dir, '*.txt')) + glob.glob(os.path.join(logs_dir, '*.json'))
            
            count = 0
            for f in log_files:
                if 'eod_sent' in f or 'sent_alerts' in f or 'cron' in f:
                    os.remove(f)
                    count += 1
                    
            messages.success(request, f"🧹 Successfully purged {count} runtime lock/log files.")
        except Exception as e:
            messages.error(request, f"❌ Error clearing logs: {e}")
            
    return redirect('control_room')

@login_required
def market_radar(request):
    signals_path = os.path.abspath(os.path.join(settings.BASE_DIR, "..", "data", "market_signals.json"))
    signals = []
    scanner_status = "OFFLINE - AWAITING BOT SCAN"
    last_scanned = None
    
    if os.path.exists(signals_path):
        try:
            timestamp = os.path.getmtime(signals_path)
            last_scanned = datetime.datetime.fromtimestamp(timestamp)
            with open(signals_path, 'r') as f:
                signals = json.load(f)
            scanner_status = "ACTIVE - SYNCHRONIZED"
        except Exception as e:
            print(f"Error reading market signals JSON: {e}")

    context = {
        'signals': signals,
        'scanner_status': scanner_status,
        'last_scanned': last_scanned,
    }
    return render(request, 'frontend/radar.html', context)

def register(request):
    """Handles new operator registration with explicit field validation."""
    if request.method == 'POST':
        username = request.POST.get('username', '').strip()
        email = request.POST.get('email', '').strip()
        password = request.POST.get('password', '')
        confirm_password = request.POST.get('confirm_password', '')
        
        if not username or not email or not password:
            messages.error(request, "All fields are required.")
            return render(request, 'frontend/register.html')
            
        if password != confirm_password:
            messages.error(request, "Password mismatch. Please verify confirmation.")
            return render(request, 'frontend/register.html')
            
        if User.objects.filter(username=username).exists():
            messages.error(request, "Operator username already registered.")
            return render(request, 'frontend/register.html')
            
        try:
            user = User.objects.create_user(username=username, email=email, password=password)
            login(request, user)
            Account.objects.get_or_create(user=user)
            messages.success(request, f"Terminal initialized. Welcome, {user.username}!")
            return redirect('dashboard')
        except Exception as e:
            messages.error(request, f"Registration failed: {e}")
            
    return render(request, 'frontend/register.html')